### PR TITLE
Add the ability to buffer metrics before sending them to unix domain socket

### PR DESCRIPTION
**Pull request by cancecen**

### CODE REVIEW

**Review by copperlight — APPROVED** [review]
This looks reasonable, thanks for the contribution!

It only buffers for the unix domain socket, but I think this is a fine starting point, since it is the higher-performance option which sees the most use. If this is needed on the UDP path, we can add that later.

The buffering starts with 1K plus a configurable amount, and the std::string can grow beyond that initial memory reservation, if needed, so we should not have to worry about losing messages.

The default buffer is zero, which maintains the previous behavior, while allowing overrides as needed for high-performance applications.

The unix socket tests check both the unbuffered and the buffered path.

A few meta points:

* Since we experienced this issue earlier, lets add a `.bazeliskrc` file to the root with `USE_BAZEL_VERSION=5.4.0`. This will make it clear which version of Bazel is needed for the project, until such time as we can upgrade to the 6+ series.
* When we merge, we will squash these commits.

**Review by copperlight — CHANGES_REQUESTED** [review]
This looks reasonable, thanks for the contribution!

It only buffers for the unix domain socket, but I think this is a fine starting point, since it is the higher-performance option which sees the most use. If this is needed on the UDP path, we can add that later.

The buffering starts with 1K plus a configurable amount, and the std::string can grow beyond that initial memory reservation, if needed, so we should not have to worry about losing messages.

The default buffer is zero, which maintains the previous behavior, while allowing overrides as needed for high-performance applications.

The unix socket tests check both the unbuffered and the buffered path.

One issue we need to think about:

* What happens when a few metrics are written, but they remain less than the configured buffer size? Currently, those updates will never be flushed.
* Typically, we handle this by flushing either based on size, or when at-most N-seconds have elapsed since the last write.

A few meta points:

* Since we experienced this issue earlier, lets add a `.bazeliskrc` file to the root with `USE_BAZEL_VERSION=5.4.0`. This will make it clear which version of Bazel is needed for the project, until such time as we can upgrade to the 6+ series.
* When we merge, we will squash these commits.

**Comment by cancecen** [comment]
> This looks reasonable, thanks for the contribution!

Thanks for taking a look.

> 
> It only buffers for the unix domain socket, but I think this is a fine starting point, since it is the higher-performance option which sees the most use. If this is needed on the UDP path, we can add that later.
> 
> The buffering starts with 1K plus a configurable amount, and the std::string can grow beyond that initial memory reservation, if needed, so we should not have to worry about losing messages.
> 
> The default buffer is zero, which maintains the previous behavior, while allowing overrides as needed for high-performance applications.
> 
> The unix socket tests check both the unbuffered and the buffered path.

Thanks for the summary, I should've written something like this!

> 
> One issue we need to think about:
> 
> * What happens when a few metrics are written, but they remain less than the configured buffer size? Currently, those updates will never be flushed.
> * Typically, we handle this by flushing either based on size, or when at-most N-seconds have elapsed since the last write.
> 
I think I could do this, but I am thinking buffering is more of a "high performance/load mode", so we should ideally not hit this case. Do you think it is possible to make it clearer that buffering should be enabled only for "high performance/load mode"?

Otherwise, as you said that's how we could implement it, but it involves the complexity of a timer thread (or we could check the timestamp next time we attempt to buffer, but then the same question stands, what if the next request to publish never comes?). Let me know what your thoughts are.

> A few meta points:
> 
> * Since we experienced this issue earlier, lets add a `.bazeliskrc` file to the root with `USE_BAZEL_VERSION=5.4.0`. This will make it clear which version of Bazel is needed for the project, until such time as we can upgrade to the 6+ series.

Will do.

> * When we merge, we will squash these commits.

Will do.

**Comment by copperlight** [comment]
RE: at-most N seconds flush

> I think I could do this, but I am thinking buffering is more of a "high performance/load mode", so we should ideally not hit this case. Do you think it is possible to make it clearer that buffering should be enabled only for "high performance/load mode"?
> 
> Otherwise, as you said that's how we could implement it, but it involves the complexity of a timer thread (or we could check the timestamp next time we attempt to buffer, but then the same question stands, what if the next request to publish never comes?). Let me know what your thoughts are.

You raise a fair point here about the implementation complexity versus the likelihood of encountering this issue for high-volume publishing. I am ok leaning towards a simpler implementation for this iteration, but if we do that, we should add a little section to the README calling out the new configuration parameter and the possibility that metrics may not be flushed for low-volume apps. Just a few sentences should do it.

**Review by dmuino — APPROVED** [review]

**Review by copperlight — APPROVED** [review]

**Comment by copperlight** [comment]
Note that this implementation is not thread safe, and does not affect the UDP publishing path. If you are publishing metrics from multiple threads through the domain socket, then the buffer will show metric names corruption that will later appear in Atlas. If you are publishing metrics from a single thread, then this works fine as-is.

**Comment by cancecen** [comment]
> Note that this implementation is not thread safe, and does not affect the UDP publishing path. If you are publishing metrics from multiple threads through the domain socket, then the buffer will show metric names corruption that will later appear in Atlas. If you are publishing metrics from a single thread, then this works fine as-is.

Good point. In our use case - we create a separate buffer per thread (via separate instances of the spectator client). It seems like [send](https://pubs.opengroup.org/onlinepubs/009695399/functions/xsh_chap02_09.html) is supposed to be thread-safe per POSIX spec. So the caller either needs a separate instance of buffer per caller thread, or perform the synchronization before writing into the buffer.

**Pull request merged**
